os: osx
osx_image: xcode9.4
cache: pip

env:
  global:
    - PYTHONFAULTHANDLER=x
    - SKIP_LATEX_BUILD=1
    - TOXENV=py37

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: "ppa:beineri/opt-qt58-trusty"
      - sourceline: "ppa:corentinjabot/cmake-backport" #cmake 3.7.2
      # cmake 3.12 ppa:dluxen/cmake-backports
    packages:
      - gcc-5
      - g++-5
      - libglu1-mesa-dev
      - qt58base
      - cmake
  homebrew:
    taps:
      - heroku/brew
      - homebrew/cask-versions
    casks: java8
    packages:
      - heroku
      - imagemagick
      - python
    brewfile: true
    update: true

before_install:
  - echo 'this is my before_install phase'

install:
  - pip install -U tox codecov

script:
  - tox -- -v

after_success:
  - if [[ -e .coverage ]]; then codecov -e $TOXENV; fi

notifications:
  email: false
