language: python
os: osx
osx_image: xcode9.4
cache: pip

env:
  global:
    - PYTHONFAULTHANDLER=x
    - SKIP_LATEX_BUILD=1
    - TOXENV=py36

install:
  - pip install -U tox codecov

script:
  - tox -- -v

after_success:
  - if [[ -e .coverage ]]; then codecov -e $TOXENV; fi
